UserInputManagerの仮実装
cyder/Aktiva-V2 pull request #13
Opened 2017-07-15 08:35 UTC by Mori-Atsushi

close #11 

以下のようにして利用する
```cs
using UserInputs;

public class hoge  : MonoBehaviour
{
  void Update()
  {
    if(UserInputManager.GetUpdateFlag(UserInputCode.AddSong)) {
      Debug.Log("AddSong!");
      AddSong addsong = (AddSong)UserInputManager.GetUserInput(UserInputCode.AddSong);
      Debug.Log(addsong.GetData(0).ToString());
    }

    if(UserInputManager.GetUpdateFlag(UserInputCode.Pause)) {
      Debug.Log("Pause!");
    }
  }
}
```

2017-07-15 08:36 UTC, Mori-Atsushi commented
色々悩んだ結果こういう形になった
もっといい感じに管理できそうだったら教えて欲しい

2017-07-16 04:31 UTC, meokz commented on Assets/Scripts/UserInputManager.cs
> +    foreach (UserInput input in userInput)
ここ foreach(var input in userInput)　の方がかっこいい

2017-07-16 04:51 UTC, meokz commented
UserInputManager.GetUpdateFlagで判定するくらいなら，イベントで発火させた方がいいんじゃないかなと思ったり

```cs
UserInputEventsArgs.cs
public class UserInputEventArgs : EventArgs {
    public string UserInputName;

    public UserInputEventArgs(string userInputName) {
        this.UserInputName = userinputName;
    }
}

```cs
UserInput.cs
class UserInput {
　public delegate void UserInputEventHandler(UserInput userInput, UserInputEventArgs e);
　public event UserInputEventHandler OnValueChanged;

　bool _updateFlag = false;
　bool updateFlag {
　　get { return _updateFlag; }
　　set {
　　　if(!_updateFlag && value && OnValueChanged != null) {
　　　　OnValueChanged(this, new UserInputEventArgs("AddSong");
　　　}
　　　_updateFlag = value;
　}
```

```cs
つかうほう
public class hoge  : MonoBehaviour {
　UserInput userInput.
　void Start() {
　　userInput.OnValueChanged += OnValueChanged;
　}

　void OnValueChanged(object sender, UserInputEventArgs e) {
　　Debug.Log(e.UserInputName); // AddSong!"
　}
}

2017-07-16 04:52 UTC, meokz commented
それか，UserInputManager.GetUpdateFlagでやるなら，せめて判定側はUniRxにしたいね。
@chigichan24 どう思う？

2017-07-16 04:58 UTC, meokz requested changes

2017-07-16 04:58 UTC, meokz commented on Assets/Scripts/UserInput/UserInput.cs
> +    public void DataUpdated()
public void OnDataUpdated()の方が分かりやすい

2017-07-16 06:09 UTC, chigichan24 commented
@meokz 素直にイベントで実装するほうがこの場合は向いてそう．

2017-07-20 09:39 UTC, Mori-Atsushi commented
eventベースで修正しました。

```cs
// 使用例
using UnityEngine;
using UnityEngine.SceneManagement;
using UserInputs;

public class RootSceneManager : MonoBehaviour
{
  UserInput userInput;

  void Start()
  {
    userInput = UserInputManager.GetUserInput(UserInputCode.AddSong);
    userInput.OnValueChanged += OnValueChanged;
  }

  void OnValueChanged(object sender, UserInputEventArgs e)
  {
    Debug.Log(e.userInputName); // AddSong!"
  }
}
```

2017-07-21 07:58 UTC, Mori-Atsushi commented
@meokz 修正しました

2017-07-21 07:59 UTC, meokz approved these changes
OK

2017-07-21 07:59 UTC, merged