addSongポップアップのデザイン
cyder/Aktiva-V2 pull request #27
Opened 2017-07-30 15:10 UTC by Mori-Atsushi

close #23

2017-08-03 11:55 UTC, meokz requested changes

2017-08-03 11:55 UTC, meokz commented on Assets/Scripts/Popup.cs
> +    popup.transform.SetParent(transform, false);
細かくて申し訳ないですけど，thisをつけて欲しいです
`popup.transform.SetParent(this.transform, false); `

2017-08-03 22:38 UTC, Mori-Atsushi commented
修正しました。

2017-08-04 12:29 UTC, meokz approved these changes

2017-08-04 12:29 UTC, merged