addSongポップアップのアニメーション
cyder/Aktiva-V2 pull request #34
Opened 2017-08-07 16:11 UTC by Mori-Atsushi

close #31

UserInputはstaticのままにしましたがどうでしょう？
SceneLoadが余計ややこしくなっています。（HELP）

2017-08-21 17:25 UTC, meokz reviewed
UserInputがstaticなのは自然だと思うので大丈夫です。

SceneLoadがややこしくなってるのは，UserInputのstaticを除いた場合でしょうか，それとも現状ややこしくなっていますか

2017-08-21 17:25 UTC, meokz commented on Assets/Scripts/PlayScene/DanceVideoPlayer.cs
> +  bool _isEnded = false;
isEnded

2017-08-21 17:25 UTC, meokz commented on Assets/Scripts/PlayScene/DanceVideoPlayer.cs
> +  public bool isEnded
IsEnded

2017-08-21 17:25 UTC, meokz commented on Assets/Scripts/PlayScene/DanceVideoPlayer.cs
> +  public bool isEnded
大文字がいいなぁ

2017-08-21 17:25 UTC, meokz commented on Assets/Scripts/RootSceneManager.cs
> +    StartCoroutine(LoadStandbyScene());
ここを大峠が読む@あとで

2017-08-21 17:27 UTC, meokz requested changes

2017-08-21 17:27 UTC, meokz commented on Assets/Scripts/RootSceneManager.cs
> +  IEnumerator LoadStandbyScene()
SceneLoadの件ここですね。

これは一つのメソッドにまとめられるのでは

2017-08-22 05:27 UTC, Mori-Atsushi commented
現状ややこしくなっております。
ロードのタイミングとGameObject.Findのタイミングが難しいって感じですね。
レビュー終わったらタグの変更をお願いします。

2017-08-22 05:28 UTC, meokz commented
@Mori-Atsushi 
なんで画面ごとにロードの関数を作ってるんだろう...

2017-08-22 05:31 UTC, Mori-Atsushi commented
PlaySceneの時にロードが終わったら実行したい処理を書くために関数化して、ほかもシーンも今後同様のケースが起こるかもとおもってそっちに統一した形

2017-08-22 16:11 UTC, Mori-Atsushi commented
修正しました。現状、プロパティ名の頭文字が大文字、小文字が混ざってますが、これは大文字に統一する方向で行きましょうか。
別部分に関してはリファクタリング用Issueを立てます。

2017-08-28 16:06 UTC, meokz commented
@Mori-Atsushi 
修正ありがとうございます。めっちゃ綺麗になりました。
書いていて混ざってるのが気持ち悪かったらそのときに直すくらいの気持ちでもいい気がしてます。今ソースコード触ってる人少ないので

2017-08-28 16:07 UTC, meokz approved these changes

2017-08-28 16:07 UTC, merged